import { prisma } from '../lib/db'

const wordsData = `a, determiner, General, A1
a.m./A.M./am/AM, adverb, General, A1
abandon, verb, General, B1
ability, noun, General, A2
able, adjective, General, B1
abnormal, adjective, General, B1
aboard, adverb, General, B1
aborigine, noun, General, B1
about, adverb, General, A1
about, preposition, General, A1
above, adjective, General, B1
above, adverb, General, A1
above, preposition, General, A1
abroad, adverb, General, A2
absence, noun, General, B1
absent, adjective, General, B1
absolute, adjective, General, B1
absolutely, adverb, General, B1
absorb, verb, General, B1
abstract, adjective, General, B1
abundance, noun, General, B1
abundant, adjective, General, B1
academic, adjective, General, B1
academy, noun, General, B1
accent, noun, General, B1
accept, verb, General, A2
acceptable, adjective, General, A2
acceptance, noun, General, B1
access, noun, General, B1
accessible, adjective, General, B1
accessory, noun, General, B1
accident, noun, General, A2
accidental, adjective, General, B1
accidentally, adverb, General, B1
accompany, verb, work, B1
accomplish, verb, General, B1
according to, preposition, General, B1
account, noun, General, A2
account, verb, General, B1
accountant, noun, General, B1
accuracy, noun, General, B1
accurate, adjective, General, B1
accurately, adverb, General, B1
accuse, verb, General, B1
accustom, verb, General, B1
ache, noun, General, B1
achieve, verb, General, A2
achievement, noun, General, B1
acknowledge, verb, General, B1
acknowledgment/acknowledgement, noun, General, B1
acquaintance, noun, General, B1
acquire, verb, General, B1
across, adverb, General, A2
across, preposition, General, A2
act, noun, General, A2
act, verb, General, B1
action, noun, General, A1
active, adjective, General, B1
activity, noun, General, A1
actor, noun, General, A1
actress, noun, General, B1
actually, adverb, General, A2
ad, noun, General, B1
adapt, verb, General, B1
add, verb, General, A1
addition, noun, General, A2
additional, adjective, General, A2
address, noun, clothes, A1
address, verb, clothes, B1
addressee, noun, clothes, B1
adjective, noun, General, A2
adjust, verb, General, A2
administration, noun, General, B1
admiration, noun, General, B1
admire, verb, General, A2
admission, noun, General, B1
admit, verb, General, A2
adopt, verb, General, B1
adorable, adjective, General, B1
adult, adjective, General, A2
adult, noun, General, A2
advance, verb, General, B1
advanced, adjective, General, A2
advantage, noun, General, A2
adventure, noun, General, A2
adverb, noun, General, B1
adverbial, adjective, General, B1
advert, noun, General, B1
advertise, verb, General, B1
advertisement, noun, General, A2
advertising, noun, General, A2
advice, noun, General, A2
advise, verb, General, A2
adviser/advisor, noun, General, B1
aerobics, noun, General, B1
affair, noun, General, A2
affect, verb, General, B1
affection, noun, General, B1
afford, verb, General, B1
afraid, adjective, General, A1
after, adverb, General, A2
after, conjunction, General, B1
after, preposition, General, A1
afternoon, noun, General, A1
afterward, adverb, General, B1
afterwards, adverb, General, B1
again, adverb, General, A1
against, preposition, General, A2
age, noun, General, A1
aged, adjective, General, A2
agency, noun, General, A2
agenda, noun, General, B1
agent, noun, General, A2
aggressive, adjective, General, B1
ago, adverb, General, A1
agree, verb, General, A1
agreement, noun, General, B1
agricultural, adjective, General, B1
agriculture, noun, General, B1
ahead, adverb, General, A2
aid, noun, General, B1
aid, verb, General, B1
aim, noun, General, B1
air, noun, General, A2
air conditioning, noun, General, B1
air force, noun, General, B1
airline, noun, General, B1
airplane/aeroplane, noun, travel, A1
airport, noun, travel, A1
aisle, noun, General, A2
alarm, noun, General, A2
alarm, verb, General, B1
alarm clock, noun, General, A2
album, noun, General, A1
alcohol, noun, General, B1
alcoholic, adjective, General, B1
alike, adjective, General, B1
alike, adverb, General, B1
alive, adjective, General, A2
all, adverb, General, A2
all, determiner, General, A1
all, pronoun, General, A1
all right, adjective, General, A1
all right, adverb, General, A1
allergic, adjective, General, B1
allow, verb, General, A2
allowance, noun, General, B1
almost, adverb, General, A1
alone, adjective, General, A2
alone, adverb, General, A1
along, adverb, General, A1
along, preposition, General, A2
aloud, adverb, General, B1
alphabet, noun, General, B1
already, adverb, General, A1
alright, adjective, General, A2
alright, adverb, General, A2
also, adverb, General, A1
alternative, adjective, General, B1
alternative, noun, General, B1
although, conjunction, General, A2
altogether, adverb, General, B1
always, adverb, General, A1
am, be-verb, General, A1
amazed, adjective, General, B1
amazing, adjective, General, B1
ambition, noun, General, A2
ambitious, adjective, General, B1
ambulance, noun, General, B1
among, preposition, General, A2
amount, noun, General, B1
amused, adjective, General, A2
amusement, noun, General, A2
amusing, adjective, General, B1
an, determiner, General, A1
analysis, noun, General, B1
analyze/analyse, verb, General, B1
ancestor, noun, General, A2
ancient, adjective, General, A2
and, conjunction, General, A1
angel, noun, General, A2
anger, noun, General, B1
angle, noun, General, B1
angrily, adverb, General, A2
angry, adjective, General, A1
animal, noun, General, A1
animated, adjective, General, B1
animation, noun, General, B1
ankle, noun, General, A2
anniversary, noun, General, A2
announce, verb, General, B1
announcement, noun, General, B1
annoy, verb, General, A2
annoyance, noun, General, B1
annoyed, adjective, General, B1
annoying, adjective, General, A2
annual, adjective, General, B1
annually, adverb, General, B1
another, determiner, General, A1
another, pronoun, General, A2
answer, noun, General, A1
answer, verb, General, A1
ant, noun, General, B1
anti, adjective, General, B1
antique, noun, General, B1
antonym, noun, General, B1
anxiety, noun, General, B1
anxious, adjective, General, A2
anxiously, adverb, General, B1
any, determiner, General, A1
any, pronoun, General, A1
anybody, pronoun, health, A1
anyhow, adverb, General, B1
anymore, adverb, General, A2
anyone, pronoun, General, A1
anything, pronoun, General, A1
anyway, adverb, General, A2
anywhere, adverb, General, A2
apart, adverb, General, A2
apartment, noun, General, A2
ape, noun, General, B1
apologize/apologise, verb, General, A2
apology, noun, General, B1
apparent, adjective, General, B1
apparently, adverb, General, A2
appeal, noun, General, B1
appear, verb, General, A2
appearance, noun, General, A2
appetite, noun, General, B1
applaud, verb, General, B1
applause, noun, General, B1
apple, noun, food, A1
application, noun, animals, B1
apply, verb, General, A2
appoint, verb, General, B1
appointment, noun, General, A2
appreciate, verb, General, A2
appreciation, noun, General, B1
approach, noun, General, B1
appropriate, adjective, General, A2
approval, noun, General, B1
approve, verb, General, B1
approximately, adverb, General, B1
April, noun, General, A1
apron, noun, General, A1
architect, noun, General, B1
architecture, noun, General, A2
are, be-verb, General, A1
area, noun, General, A2
argue, verb, General, A2
argument, noun, General, A2
arise, verb, General, B1
arithmetic, noun, General, B1
arm, noun, General, A1
arm, verb, General, B1
armchair, noun, General, A2
armed, adjective, General, A2
army, noun, General, B1
around, adverb, General, A2
around, preposition, General, A1
arrange, verb, General, B1
arrangement, noun, General, B1
arrest, noun, General, B1
arrest, verb, General, B1
arrival, noun, General, B1
arrive, verb, General, A1
arrow, noun, General, B1
art, noun, General, A1
article, noun, General, A1
artificial, adjective, General, A2
artist, noun, General, B1
artistic, adjective, General, B1
as, conjunction, General, A2
as, preposition, General, A1
ashamed, adjective, General, B1
aside, adverb, General, B1
ask, verb, General, A1
asleep, adjective, General, A2
aspect, noun, General, B1
aspirin, noun, General, B1
assign, verb, General, B1
assignment, noun, General, B1
assist, verb, General, B1
assistance, noun, General, B1
assistant, adjective, General, A2
assistant, noun, General, B1
associate, verb, General, B1
association, noun, General, A2
assume, verb, General, B1
astronaut, noun, General, A2
astronomer, noun, General, B1
at, preposition, General, A1
athlete, noun, General, A2
athletic, adjective, General, B1
Atlantic, adjective, General, B1
atmosphere, noun, General, B1
atom, noun, General, A2
atomic, adjective, General, B1
attach, verb, General, B1
attachment, noun, General, B1
attack, noun, General, A2
attack, verb, General, A2
attain, verb, General, B1
attempt, noun, General, A2
attempt, verb, General, B1
attend, verb, General, B1
attention, noun, General, A2
attitude, noun, General, A2
attract, verb, General, B1
attraction, noun, General, B1
attractive, adjective, General, A2
audience, noun, General, A2
audio, adjective, General, A2
August, noun, General, A1
aunt, noun, General, A1
author, noun, General, A2
authority, noun, General, B1
automatic, adjective, General, A2
automatically, adverb, General, A2
autumn, noun, General, A1
auxiliary, adjective, General, B1
available, adjective, General, B1
avenue, noun, General, B1
average, adjective, General, A2
average, noun, General, A2
avoid, verb, General, A2
awake, adjective, General, A1
award, noun, General, A2
award, verb, General, B1
aware, adjective, General, B1
awareness, noun, General, B1
away, adverb, General, A1
awesome, adjective, General, B1
awful, adjective, General, A2
awkward, adjective, General, B1
baby, noun, General, A1
babysit, verb, General, B1
babysitter, noun, General, B1
back, adjective, General, A2
back, adverb, General, A1
back, noun, General, A1
back, verb, General, B1
backache, noun, General, B1
background, noun, General, A2
backpack, noun, General, B1
backpacker, noun, General, B1
backpacking, noun, General, B1
bacon, noun, General, B1
bad, adjective, General, A1
badly, adverb, General, A2
badminton, noun, General, A2
bag, noun, General, A1
baggage, noun, General, B1
bake, verb, General, A2
baker, noun, General, B1
bakery, noun, General, B1
balance, noun, General, B1
balcony, noun, General, A2
bald, adjective, General, B1
ball, noun, sports, A1
balloon, noun, sports, A2
banana, noun, General, A1
band, noun, General, A1
bandage, noun, General, B1
bang, noun, General, B1
bang, verb, General, B1
bank, noun, General, A1
bank, verb, General, A2
bank account, noun, General, B1
banking, noun, General, A2
bar, noun, General, A1
bar, verb, General, B1
barbecue, noun, General, A2
barbecue, verb, General, B1
barber, noun, General, A2
bare, adjective, General, B1
barely, adverb, General, B1
bargain, noun, General, A2
bark, noun, General, B1
barman, noun, General, B1
barrel, noun, General, B1
base, noun, General, A2
base, verb, General, B1
baseball, noun, sports, A1
basement, noun, General, B1
basic, adjective, General, A2
basically, adverb, General, A2
basin, noun, General, B1
basis, noun, General, B1
basket, noun, General, A2
basketball, noun, sports, A1
bat, noun, General, A1
bat, verb, General, B1
batch, noun, General, A2
bath, noun, General, A1
bathe, verb, General, B1
bathroom, noun, General, A1
battery, noun, General, A2
battle, noun, General, B1
bay, noun, General, A2
be, be-verb, General, A1
beach, noun, General, A1
bean, noun, General, A1
bear, noun, animals, A1
bear, verb, animals, A2
beard, noun, animals, B1
beast, noun, General, B1
beat, verb, food, B1
beautiful, adjective, General, A1
beautifully, adverb, General, B1
beauty, noun, General, A2
beaver, noun, General, B1
because, conjunction, General, A1
because of, preposition, General, B1
become, verb, General, A1
bed, noun, General, A1
bedroom, noun, General, A1
bedside, noun, General, B1
bee, noun, General, A1
beef, noun, General, A1
been, be-verb, General, A2
beer, noun, General, A2
before, adverb, General, A1
before, conjunction, General, A2
before, preposition, General, A1
beg, verb, General, A2
begin, verb, General, A1
beginner, noun, General, A2
beginning, noun, General, A2
behalf, noun, General, B1
behave, verb, General, B1
behavior/behaviour, noun, General, A2
behind, adverb, General, A1
behind, preposition, General, A1
being, noun, General, A2
belief, noun, General, B1
believe, verb, General, A1
bell, noun, General, A1
belly, noun, General, A2
belong, verb, General, A2
beloved, adjective, General, B1
below, adverb, General, A1
below, preposition, General, A1
belt, noun, clothes, A2
bench, noun, General, A2
bend, verb, General, A2
beneath, preposition, food, B1
benefit, noun, General, B1
bent, adjective, General, B1
beside, preposition, General, A1
besides, adverb, General, A2
besides, preposition, General, B1
best, adjective, General, A1
best, adverb, General, A1
bet, verb, General, B1
better, adjective, General, A1
better, adverb, General, A2
between, preposition, General, A1
beyond, preposition, General, A2
bicycle, noun, General, A1
big, adjective, General, A1
bike, noun, General, A1
bilingual, adjective, General, B1
bill, noun, General, A2
bill, verb, General, B1
bin, noun, General, B1
biochemistry, noun, General, B1
biography, noun, General, B1
biology, noun, General, B1
bird, noun, animals, A1
birth, noun, General, A1
birthday, noun, General, A1
biscuit, noun, General, A1
bishop, noun, General, B1
bit, noun, General, A2
bite, noun, General, A2
bite, verb, General, B1
bitter, adjective, General, B1
black, adjective, General, A1
black, noun, General, A1
blackboard, noun, General, A2
blame, noun, General, B1
blame, verb, General, A2
blank, adjective, General, A1
blanket, noun, General, A2
bleed, verb, General, B1
blend, verb, General, B1
bless, verb, General, B1
blessing, noun, General, B1
blind, adjective, General, B1
block, noun, General, A1
block, verb, General, B1
blog, noun, General, B1
blogger, noun, General, B1
blonde, adjective, General, A2
blood, noun, General, A2
bloom, noun, General, A2
blow, noun, General, A2
blow, verb, General, A1
blue, adjective, General, A1
blue, noun, General, A1
blush, noun, General, B1
board, noun, General, A1
board, verb, General, B1
board game, noun, sports, A2
boast, verb, General, B1
boat, noun, General, A1
body, noun, health, A1
boil, verb, General, A2
boiled, adjective, General, A2
bold, adjective, General, B1
boldly, adverb, General, B1
bomb, noun, General, B1
bomb, verb, General, B1
bond, noun, General, B1
bone, noun, General, A1
bonus, noun, General, A2
book, noun, General, A1
book, verb, General, B1
bookcase, noun, General, A2
booking, noun, General, B1
bookshelf, noun, General, A2
bookshop, noun, General, A2
bookstore, noun, General, A1
boom, noun, General, B1
boot, noun, General, B1
border, noun, General, B1
bore, verb, General, B1
bored, adjective, General, A2
boredom, noun, General, B1
boring, adjective, General, A1
borrow, verb, General, A1
boss, noun, General, A2
both, adverb, General, A1
both, determiner, General, A1
both, pronoun, General, A1
bother, noun, General, B1
bother, verb, General, A2
bottle, noun, General, A1
bottom, noun, General, A1
bounce, verb, General, B1
bound, adjective, General, B1
bow, noun, General, B1
bowl, noun, General, A1
bowl, verb, General, B1
box, noun, General, A1
boxing, noun, General, B1
boy, noun, General, A1
boyfriend, noun, General, A1
bra, noun, General, A2
bracelet, noun, sports, B1
brain, noun, General, A1
brainstorm, noun, General, A2
brainstorming, noun, General, B1
brake, noun, General, A2
branch, noun, General, A2
branch, verb, General, B1
brand, noun, General, A2
brand-new, adjective, General, B1
brass, noun, General, B1
brave, adjective, General, A2
bravely, adverb, General, B1
bread, noun, food, A1
break, noun, General, A2
break, verb, General, A1
breakfast, noun, General, A1
breakthrough, noun, General, B1
breast, noun, General, B1
breath, noun, food, B1
breathe, verb, food, A1
breathless, adjective, food, B1
breed, verb, General, B1
breeding, noun, General, B1
breeze, noun, General, A2
brick, noun, General, B1
bride, noun, General, A2
bridge, noun, General, A1
brief, adjective, General, B1
briefly, adverb, General, B1
bright, adjective, General, A1
brightly, adverb, General, B1
brilliant, adjective, General, A2
bring, verb, General, A1
broad, adjective, General, B1
broadcast, noun, General, B1
broccoli, noun, General, B1
broken, adjective, General, A1
bronze, noun, General, B1
brother, noun, General, A1
brotherhood, noun, General, B1
brown, adjective, General, A1
brown, noun, General, A2
brush, noun, General, A1
brush, verb, General, A1
bubble, noun, General, B1
bucket, noun, General, A1
buddy, noun, General, B1
budget, noun, General, A2
bug, noun, General, A2
build, verb, General, A1
builder, noun, General, B1
building, noun, General, A1
bulb, noun, General, A2
bull, noun, General, B1
bullet, noun, General, B1
bulletin, noun, General, B1
bump, verb, General, B1
bunch, noun, General, B1
burden, noun, General, B1
bureau, noun, General, B1
burger, noun, General, A1
burglar, noun, General, B1
burn, noun, General, A2
burn, verb, General, B1
burning, adjective, General, B1
burst, verb, General, B1
bury, verb, General, A2
bus, noun, travel, A1
bus station, noun, travel, A2
bus stop, noun, travel, A2
bush, noun, travel, A2
business, noun, travel, A1
businessman, noun, travel, A2
businesswoman, noun, travel, A2
bust, verb, travel, B1
busy, adjective, travel, A1
but, conjunction, General, A1
but, preposition, General, B1
butcher, noun, General, B1
butter, noun, General, A1
butterfly, noun, General, A1
button, noun, General, A1
buy, verb, General, A1
buyer, noun, General, B1
by, preposition, General, A1
bye, noun, General, A1
cab, noun, General, A2
cabbage, noun, General, B1
cabin, noun, General, B1
cafe/café, noun, General, A1
cafeteria, noun, General, A2
cage, noun, General, B1
cake, noun, General, A1
calculate, verb, General, B1
calculation, noun, General, B1
calculator, noun, General, B1
calendar, noun, General, A2
calf, noun, General, B1
call, noun, General, A1
call, verb, General, A2
caller, noun, General, B1
calm, adjective, General, B1
calmness, noun, General, B1
camel, noun, General, B1
camera, noun, General, A1
camp, noun, General, A1
camp, verb, General, A2
camping, noun, General, A2
campsite, noun, General, B1
campus, noun, General, A2
can, modal auxiliary, General, A1
can, noun, General, A2
canal, noun, General, B1
cancel, verb, General, B1
cancer, noun, General, B1
candle, noun, General, B1
candy, noun, General, A1
canned, adjective, General, B1
canteen, noun, General, B1
cap, noun, General, A1
capable, adjective, General, B1
capacity, noun, General, B1
capital, noun, General, A2
capital letter, noun, General, A2
capsule, noun, General, B1
captain, noun, General, A2
capture, noun, General, B1
capture, verb, General, B1
car, noun, travel, A1
car park, noun, travel, A2
card, noun, travel, A1
care, noun, travel, A1
care, verb, travel, B1
career, noun, travel, B1
careful, adjective, travel, A1
carefully, adverb, travel, A1
careless, adjective, travel, B1
carelessly, adverb, travel, B1
carelessness, noun, travel, B1
carpet, noun, travel, B1
carriage, noun, travel, B1
carrot, noun, travel, A2
carry, verb, travel, A1
carton, noun, travel, B1
cartoon, noun, travel, A1
case, noun, General, A1
cash, noun, General, A2
cashpoint, noun, General, B1
cassette, noun, General, A2
castle, noun, General, A2
casual, adjective, General, B1
cat, noun, animals, A1
catch, noun, animals, A1
catch, verb, animals, A1
categorize/categorise, verb, animals, B1
category, noun, animals, B1
cattle, noun, animals, B1
cause, verb, General, A2
caution, noun, General, B1
cautious, adjective, General, B1
cave, noun, General, B1
CD, noun, General, A1
CD player, noun, sports, A1
CD-ROM, noun, General, B1
celebrate, verb, General, A1
celebration, noun, General, A1
celebrity, noun, General, B1
cell, noun, General, B1
cent, noun, General, A2
center/centre, noun, General, A2
centimeter/centimetre, noun, General, A2
central, adjective, General, B1
central heating, noun, food, B1
century, noun, General, A2
cereal, noun, General, A2
ceremony, noun, General, B1
certain, adjective, General, A2
certainly, adverb, General, A2
certainty, noun, General, B1
chain, noun, General, A2
chair, noun, General, A1
chairman, noun, General, A2
challenge, noun, General, A2
challenging, adjective, General, B1
champagne, noun, General, A2
champion, noun, General, B1
championship, noun, General, A2
chance, noun, General, A2
change, noun, General, A1
change, verb, General, A1
channel, noun, General, B1
chaos, noun, General, B1
chapter, noun, General, A2
character, noun, General, A1
characteristic, noun, General, B1
characterize/characterise, verb, General, B1
charge, noun, General, B1
charge, verb, General, B1
chariot, noun, General, B1
charity, noun, General, B1
charm, noun, General, B1
chart, noun, General, A2
chase, noun, General, B1
chat, noun, clothes, B1
chat, verb, clothes, A2
chat show, noun, clothes, B1
cheap, adjective, General, A2
check, noun, General, A1
check, verb, General, A2
check-in counter/check-in, noun, General, B1
check-in desk/check-in, noun, General, B1
checkout, noun, General, B1
cheek, noun, General, A2
cheer, verb, General, A2
cheerful, adjective, General, B1
cheese, noun, General, A1
chef, noun, General, A2
chemical, adjective, General, A2
chemical, noun, General, B1
chemist, noun, General, B1
chemistry, noun, General, B1
cheque, noun, General, A2
cherish, verb, General, B1
chess, noun, General, A2
chest, noun, General, A2
chest of drawers, noun, General, B1
chewing gum, noun, sports, B1
chicken, noun, General, A1
chief, adjective, General, B1
child, noun, General, A1
childhood, noun, General, A2
chili/chilli, noun, General, A2
chimpanzee, noun, General, A2
chin, noun, General, A2
chirp, noun, General, A2
chocolate, noun, General, A1
choice, noun, General, A2
choir, noun, General, B1
choke, verb, General, B1
choose, verb, General, A1
Christian, adjective, General, B1
chronological, adjective, General, B1
chuckle, noun, General, B1
church, noun, General, A1
cigarette, noun, General, A2
cinema, noun, General, A1
circle, noun, General, A1
circle, verb, General, B1
circular, adjective, General, B1
circus, noun, General, B1
citizen, noun, General, A2
citizenship, noun, General, B1
city, noun, General, A1
civil, adjective, General, B1
civilization/civilisation, noun, General, B1
claim, noun, General, B1
claim, verb, General, A2
class, noun, General, A1
classic, adjective, General, A2
classical, adjective, General, B1
classical music, noun, General, A2
classify, verb, General, B1
classmate, noun, General, A1
classroom, noun, General, A1
clean, adjective, General, A1
clean, verb, General, A1
cleaner, noun, General, A2
clear, adjective, General, A2
clear, verb, General, B1
clearly, adverb, General, A2
clerk, noun, General, A2
clever, adjective, General, A1
click, noun, General, B1
click, verb, General, A2
cliff, noun, General, B1
climate, noun, General, B1
climb, noun, General, A1
climb, verb, General, A2
climber, noun, General, B1
climbing, noun, General, A2
clinic, noun, General, B1
clip, noun, General, B1
clock, noun, General, A1
clone, verb, General, A2
close, adjective, General, A1
close, verb, General, A1
closed, adjective, General, A1
closely, adverb, General, B1
cloth, noun, General, A1
clothes, noun, General, A1
cloud, noun, General, A1
cloudy, adjective, General, A1
clown, noun, General, A2
club, noun, General, A1
clue, noun, General, A2
coach, noun, General, A1
coal, noun, General, B1
coast, noun, General, A2
coast, verb, General, B1
coastal, adjective, General, B1
coat, noun, clothes, A1
cod, noun, General, B1
code, noun, General, A1
coffee, noun, General, A1
coffin, noun, General, B1
coin, noun, General, A2
coke, noun, General, A1
cola, noun, General, A2
cold, adjective, General, A1
cold, noun, General, A1
collapse, noun, General, B1
collar, noun, General, B1
collect, verb, General, A1
collection, noun, General, A1
college, noun, General, A1
color/colour, noun, General, A1
color/colour, verb, General, A1
colorful/colourful, adjective, General, A2
column, noun, General, A2
columnist, noun, General, B1
comb, noun, General, A2
combination, noun, General, B1
combine, verb, General, B1
come, verb, General, A1
comedian, noun, General, B1
comedy, noun, General, B1
comet, noun, General, B1
comfort, noun, General, B1
comfortable, adjective, General, A2
comic, adjective, General, A2
comic, noun, General, A2
comma, noun, General, B1
command, noun, General, B1
comment, noun, General, B1
commercial, adjective, General, B1
commit, verb, General, B1
commitment, noun, General, A2
committee, noun, General, A2
common, adjective, General, A2
common sense, noun, General, B1
commonly, adverb, General, B1
communicate, verb, animals, A2
communication, noun, animals, A2
companion, noun, General, B1
company, noun, work, A2
comparative, noun, General, A2
compare, verb, General, A2
comparison, noun, General, B1
compete, verb, General, B1
competition, noun, General, A2
competitive, adjective, General, B1
competitor, noun, General, B1
complain, verb, General, A2
complaint, noun, General, A2
complement, noun, General, B1
complete, adjective, General, A2
complete, verb, General, B1
completely, adverb, General, B1
complex, adjective, General, B1
complicate, verb, animals, B1
complicated, adjective, animals, B1
compliment, noun, General, B1
compose, verb, General, B1
composer, noun, General, A2
composition, noun, General, B1
compound, noun, General, B1
compromise, noun, General, B1
computer, noun, technology, A1
concentrate, verb, General, A2
concentration, noun, General, B1
concept, noun, General, B1
concern, noun, General, A2
concerned, adjective, General, B1
concert, noun, General, A1
conclude, verb, General, B1
conclusion, noun, General, B1
condition, noun, General, A2
conduct, noun, General, B1
confidence, noun, General, B1
confident, adjective, General, A2
confirm, verb, General, B1
confirmation, noun, General, B1
conflict, noun, General, B1
confuse, verb, General, A2
confused, adjective, General, A2
confusing, adjective, General, B1
confusion, noun, General, B1
congratulate, verb, General, B1
connect, verb, General, B1
connection/connexion, noun, General, B1
conquer, verb, General, B1
conscious, adjective, General, B1
consequence, noun, General, A2
consequently, adverb, General, B1
conservation, noun, General, B1
conservative, adjective, General, B1
consider, verb, General, A2
considerable, adjective, General, B1
consideration, noun, General, B1
consist, verb, General, A2
consonant, noun, General, B1
constantly, adverb, General, B1
constitute, verb, General, B1
constitution, noun, General, B1
construct, verb, General, B1
construction, noun, General, B1
consume, verb, General, B1
consumer, noun, General, B1
consumption, noun, General, B1
contact, noun, General, A2
contact, verb, General, A2
contain, verb, General, B1
container, noun, General, A2
content, noun, General, B1
contest, noun, General, A1
context, noun, General, A2
continent, noun, General, A2
continual, adjective, General, B1
continually, adverb, General, B1
continue, verb, General, A2
continuous, adjective, General, B1
continuously, adverb, General, B1
contrary, adjective, General, B1
contrast, noun, General, A2
contribute, verb, General, B1
contribution, noun, General, B1
control, noun, General, A2
control, verb, General, B1
controversial, adjective, General, B1
convenience, noun, General, A2
convenient, adjective, General, A2
conversation, noun, General, A1
convey, verb, General, B1
convince, verb, General, B1
cook, noun, food, A1
cook, verb, food, A1
cooker, noun, food, A2
cookie, noun, food, A1
cooking, noun, food, A2
cool, adjective, General, A1
cooler, noun, General, A2
cop, noun, General, A1
copy, noun, General, A1
copy, verb, General, A2
copyright, noun, General, B1
corn, noun, General, A1
corner, noun, General, A1
correct, adjective, General, A1
correction, noun, General, B1
correctly, adverb, General, A2
cost, noun, General, A2
cost, verb, General, A2
cotton, noun, General, B1
couch, noun, General, A1
cough, verb, General, B1
could, modal auxiliary, General, A1
council, noun, General, B1
counseling/counselling, noun, General, B1
count, noun, General, B1
count, verb, General, A2
counter, verb, General, B1
countless, adjective, General, B1
country, noun, General, A2
countryside, noun, General, A2
county, noun, General, B1
couple, noun, General, A2
courage, noun, General, B1
courageous, adjective, General, B1
courgette, noun, General, B1
course, noun, General, A1
court, noun, General, A2
cousin, noun, General, A1
cover, noun, General, A1
cover, verb, General, A2
cow, noun, animals, A1
craft, noun, General, B1
crash, noun, General, B1
crash, verb, General, B1
crazy, adjective, General, A2
cream, adjective, General, A2
cream, noun, General, A1
create, verb, food, A2
creative, adjective, food, A2
creativity, noun, food, A2
creator, noun, food, B1
creature, noun, food, A2
credit, noun, General, A2
credit card, noun, travel, A1
cricket, noun, General, A2
crime, noun, General, A2
criminal, noun, General, B1
crisis, noun, General, B1
crisp, noun, General, A2
critic, noun, General, B1
critical, adjective, General, B1
criticize/criticise, verb, General, A2
crop, noun, General, B1
cross, noun, General, A2
cross, verb, General, A2
crossing, noun, General, B1
crossroads, noun, General, B1
crow, noun, General, B1
crowd, noun, General, A2
crowded, adjective, General, A2
crown, noun, General, A2
cruel, adjective, General, B1
cruise, noun, General, A2
crush, noun, General, B1
cry, noun, General, A1
cry, verb, General, A2
cucumber, noun, General, B1
cultivate, verb, General, B1
cultural, adjective, General, B1
culture, noun, General, A1
cup, noun, General, A1
cupboard, noun, General, A2
cure, noun, General, B1
curiosity, noun, General, B1
curious, adjective, General, B1
curiously, adverb, General, B1
curly, adjective, General, B1
currency, noun, General, B1
current, adjective, General, B1
currently, adverb, General, B1
curriculum, noun, General, B1
curry, noun, General, A2
curse, noun, General, A2
curtain, noun, General, B1
curve, noun, General, B1
cushion, noun, General, B1
custom, noun, General, A2
customer, noun, General, A2
customs, noun, General, B1
cut, noun, General, B1
cut, verb, General, A1
cute, adjective, General, A1
CV, noun, General, B1
cycle, noun, General, B1
cycle, verb, General, B1
cycling, noun, General, A2
dad, noun, General, A1
daddy, noun, General, A1
daily, adjective, General, A2
daily, adverb, General, A2
daisy, noun, General, B1
dam, noun, General, A2
damage, noun, General, B1
damage, verb, General, B1
damaged, adjective, General, B1
damp, adjective, General, B1
dance, noun, General, A1
dance, verb, General, A1
dancer, noun, General, A2
dancing, noun, General, A1
danger, noun, General, A2
dangerous, adjective, General, A2
dangerously, adverb, General, B1
dare, verb, General, B1
dark, adjective, General, A1
darkness, noun, General, B1
date, noun, General, A1
date, verb, General, B1
dating, noun, General, B1
daughter, noun, General, A1
day, noun, General, A1
daylight, noun, General, A2
daze, noun, General, B1
dazzle, noun, General, B1
dead, adjective, General, A2
deadline, noun, General, B1
deadly, adjective, General, B1
deaf, adjective, General, B1
deal, noun, General, A2
deal, verb, General, B1
dealer, noun, General, B1
dear, adjective, General, A1
death, noun, food, A2
debate, noun, General, A2
debris, noun, General, B1
debt, noun, General, B1
December, noun, General, A1
decide, verb, General, A2
decision, noun, General, B1
declaration, noun, General, B1
declare, verb, General, B1
decline, noun, General, B1
decrease, noun, General, B1
decrease, verb, General, B1
dedicate, verb, animals, B1
deed, noun, General, B1
deep, adverb, General, A2
deeply, adverb, General, A2
defeat, verb, food, B1
defend, verb, General, B1
defender, noun, General, B1
defense/defence, noun, General, B1
deficiency, noun, General, B1
define, verb, General, B1
definite, adjective, General, B1
definite article, noun, General, B1
definitely, adverb, General, B1
definition, noun, General, B1
degree, noun, General, A2
delay, noun, General, A2
delay, verb, General, B1
delete, verb, General, B1
delicate, adjective, animals, B1
delicious, adjective, General, A1
delight, noun, General, B1
delighted, adjective, General, B1
delightful, adjective, General, B1
deliver, verb, General, B1
delivery, noun, General, B1
demand, noun, General, B1
demand, verb, General, B1
democracy, noun, General, B1
democratic, adjective, General, B1
demonstrate, verb, General, B1
demonstration, noun, General, B1
dentist, noun, General, A2
deny, verb, General, B1
depart, verb, General, B1
department, noun, General, B1
department store, noun, General, A2
departure, noun, General, B1
depend, verb, General, A2
dependent, adjective, General, B1
deposit, noun, General, B1
depressed, adjective, General, B1
depressing, adjective, General, B1
depression, noun, General, B1
deprive, verb, General, B1
depth, noun, General, B1
derive, verb, General, B1
describe, verb, General, A1
description, noun, General, A2
desert, noun, General, A2
deserve, verb, General, B1
design, noun, General, A1
design, verb, General, B1
designer, noun, General, B1
desire, noun, General, B1
desk, noun, General, A1
despair, noun, General, B1
desperate, adjective, General, B1
despite, preposition, General, B1
dessert, noun, General, A2
destination, noun, General, B1
destroy, verb, General, A2
destruction, noun, General, B1
destructive, adjective, General, B1
detail, noun, General, A2
detective, noun, General, B1
determination, noun, General, B1
determine, verb, General, B1
devastate, verb, General, B1
devastating, adjective, General, B1
develop, verb, General, A2
developed, adjective, General, A2
development, noun, General, B1
device, noun, technology, B1
devotion, noun, General, B1
diagram, noun, General, B1
dial, noun, General, B1
dial, verb, General, B1
dialog/dialogue, noun, General, B1
diameter, noun, General, B1
diamond, noun, General, A2
diaper, noun, General, B1
diary, noun, General, A2
dictionary, noun, General, A1
did, do-verb, General, A1
die, verb, General, A2
diet, noun, General, A2
differ, verb, General, B1
difference, noun, General, A1
different, adjective, General, A1
differently, adverb, General, A2
difficult, adjective, General, A1
difficulty, noun, General, A2
dig, noun, General, A1
dig, verb, General, B1
digital, adjective, General, B1
digital camera, noun, General, A2
diligence, noun, General, B1
diligent, adjective, General, B1
dining room, noun, General, A1
dinner, noun, food, A1
dinosaur, noun, General, A2
dioxide, noun, General, B1
direct, adjective, General, A2
direct, verb, General, B1
direction, noun, General, A2
directly, adverb, General, B1
director, noun, General, A2
dirt, noun, General, B1
dirty, adjective, General, A1
disability, noun, General, B1
disable, verb, General, B1
disabled, adjective, General, B1
disadvantage, noun, General, A2
disagree, verb, General, A2
disagreement, noun, General, B1
disappear, verb, General, A2
disappoint, verb, General, B1
disappointed, adjective, General, A2
disappointing, adjective, General, A2
disappointment, noun, General, B1
disaster, noun, General, B1
disastrous, adjective, General, B1
disc jockey/disk jockey, noun, General, B1
disco, noun, General, A2
discomfort, noun, General, B1
discount, noun, General, B1
discourage, verb, General, B1
discover, verb, General, A2
discovery, noun, General, B1
discrimination, noun, General, B1
discuss, verb, General, A1
discussion, noun, General, A2
disease, noun, health, B1
disgusting, adjective, General, B1
dish, noun, General, A1
dishonest, adjective, General, A2
dishwasher, noun, General, B1
disk/disc, noun, General, B1
dislike, noun, General, A2
dislike, verb, General, B1
display, noun, sports, A2
display, verb, sports, B1
dissolve, verb, General, B1
distance, noun, General, B1
distant, adjective, General, B1
distinction, noun, General, B1
distinctly, adverb, General, B1
distinguish, verb, General, B1
distribute, verb, General, B1
distribution, noun, General, B1
district, noun, General, B1
disturb, verb, General, A2
disturbance, noun, General, B1
dive, noun, General, B1
dive, verb, General, B1
diver, noun, General, B1
diverse, adjective, General, B1
divide, noun, General, B1
divide, verb, General, A2
divine, adjective, General, B1
diving, noun, General, B1
divorced, adjective, General, B1
dizzy, adjective, General, A2
DJ, noun, General, B1
do, do-verb, General, A1
doc, noun, General, B1
doctor/Dr./Dr, noun, work, A1
document, noun, General, B1
documentary, noun, General, B1
does, do-verb, General, A1
dog, noun, animals, A1
doing, do-verb, General, A1
doll, noun, General, A1
dollar, noun, General, A1
dolphin, noun, General, B1
done, do-verb, General, A2
door, noun, General, A1
dot, noun, General, B1
double, adjective, General, A2
doubt, noun, General, A2
down, adverb, General, A1
down, preposition, General, A2
download, verb, General, A2
downstairs, adjective, General, B1
downstairs, adverb, General, A2
downtown, adverb, General, A2
downward, adjective, General, B1
doze, noun, General, B1
dozen, determiner, General, B1
dozen, noun, General, B1
drag, verb, General, B1
drama, noun, General, A1
dramatic, adjective, General, B1
draw, noun, General, A2
draw, verb, General, A1
drawer, noun, General, A2
drawing, noun, sports, A2
dream, noun, General, A1
dream, verb, General, A2
dress, noun, clothes, A1
dress, verb, clothes, A2
dressed, adjective, clothes, A2
drill, noun, General, A2
drink, noun, General, A1
drink, verb, General, A1
drive, noun, travel, A1
drive, verb, travel, A2
driver, noun, travel, A1
driver's license/driving licence, noun, travel, A2
drop, noun, General, A2
drop, verb, General, A1
drown, verb, General, B1
drug, noun, General, A2
drugstore, noun, General, A2
drum, noun, General, A1
drunk, adjective, sports, B1
dry, adjective, General, A1
dry, verb, General, A2
duck, noun, General, A2
dude, noun, General, B1
due, adjective, General, A1
dull, adjective, General, B1
dump, noun, General, B1
dump, verb, General, B1
during, preposition, General, A2
dust, noun, General, A2
dustbin, noun, General, B1
dusty, adjective, General, B1
duty, noun, General, B1
duty-free, adjective, General, B1
duvet, noun, General, B1
DVD, noun, General, A1
dynasty, noun, General, B1`

async function main() {
  const lines = wordsData.trim().split('\n')
  
  let imported = 0
  let skipped = 0

  for (const line of lines) {
    const parts = line.split(', ')
    if (parts.length < 4) continue
    
    const word = parts[0].trim()
    const partOfSpeech = parts[1].trim()
    const category = parts[2].trim()
    const level = parts[3].trim()
    
    const tags = JSON.stringify([partOfSpeech, category, level])
    
    try {
      const existingWord = await prisma.word.findFirst({
        where: { word, senseIndex: 0 }
      })

      if (existingWord) {
        await prisma.word.update({
          where: { id: existingWord.id },
          data: { tags }
        })
      } else {
        await prisma.word.create({
          data: {
            word,
            senseIndex: 0,
            tags,
            phonetic: null,
            images: '[]',
            scenario: null,
            scenarioImages: '[]',
            exampleSentence: null,
            emotionalConnection: null,
          }
        })
      }
      imported++
    } catch (e) {
      skipped++
    }
  }

  console.log(`Word bank imported successfully!`)
  console.log(`Imported: ${imported} words`)
  console.log(`Skipped: ${skipped} words`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
